### ISSUE TITLE
config.toml  怎么配置

### ISSUE THREAD

**Issue by monday99** [xdusongwei/HODL#1]
config.toml  怎么配置

**Comment by xdusongwei** [comment]
``` toml
# 根配置在 VariableTools 中定义
manager_state_path = ".../manager.json"
earning_json_path = ".../earning.json"
db_path = ".../data.db"
async_market_status = true
earning_csv_weeks = 6
html_file_path = ".../state.html"
html_auto_refresh_time = 300000
log_root = ".../logs/hodl"

# 每个持仓的部分在 StoreConfig 中定义
[store.AAPL_futu]
region = "US"
currency = "USD"
broker = "futu"
symbol = "AAPL"
trade_strategy = "hodl"
trade_type = "stock"
name = "apple"
enable = true
visible = true
max_shares = 12345
state_file_path = ".../state-{broker}-{symbol}-stage{stage}.json"
state_archive_folder = ".../hodl/archive-{broker}-{symbol}"
buy_spread_rate = 0.0
sell_spread_rate = 0.004
buy_order_rate = 0.002
sell_order_rate = 0.002
precision = 2
shares_per_unit = 1
booting_check = true
base_price_last_buy = true
base_price_last_buy_days = 21
base_price_day_low = true
base_price_tumble_protect = true
base_price_using_broker = true
tumble_protect_day_range = 7
tumble_protect_rsi = true
tumble_protect_rsi_unlock_limit = 75
tumble_protect_rsi_warning_limit = 25
lock_position = true
price_rate = 1.0
rework_level = 1
market_price_rate = 0.005
sleep_mode = true

# 每家券商的参数在 BrokerApiBase.on_init 方法中定义
[broker.tiger]
pk_path = ".../sk.pem"
tiger_id = ""
account = ""
timeout = 8

[broker.futu]
host = ""
port = 1234
# 如果交易网关和该服务不在一个机器上, 得按富途的方式生成通信私钥文件
pk_path = ".../sk.pem"

[broker.longport]
app_key = ''
app_secret = ''
# 需要指定一个文件位置, 以便存储刷新token
token_path = '.../longport_accesstoken.toml'
auto_refresh_token = true

[broker.interactiveBrokers]
connection_type = "TWS"
host = ""
port = 1234
timeout = 5
client_id = 1234
account_id = "U..."

# 券商功能自定义
# 不炒港股, 所以实际上仅支持美股交易
[[broker_meta.tiger]]
trade_type = 'stock'
share_market_state = true
share_quote = true
market_status_regions = ['US', 'HK', 'CN', ]
quote_regions = ['US', ]
trade_regions = ['US', 'HK', ]
vix_symbol = 'VIX'

[[broker_meta.futu]]
trade_type = 'stock'
share_market_state = true
share_quote = true
market_status_regions = ['US', 'HK', 'CN', ]
quote_regions = ['HK', 'CN', ]
trade_regions = ['US', ]

[[broker_meta.longport]]
trade_type = 'stock'
share_market_state = false
share_quote = true
market_status_regions = []
quote_regions = ['CN', 'HK', ]
trade_regions = ['US', ]

[[broker_meta.interactiveBrokers]]
trade_type = 'stock'
share_market_state = false
share_quote = false
market_status_regions = []
quote_regions = []
trade_regions = ['US', ]
```
